# Generated by Django 5.0.3 on 2025-03-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="data_files/"),
        ),
    ]
