# Generated by Django 5.0.3 on 2025-03-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_data_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="file",
            new_name="files",
        ),
    ]
