# Generated by Django 5.0.3 on 2025-03-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_rename_file_data_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="files",
        ),
    ]
